/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curd_tarea;


/**
 *
 * @author PC
 */
public class AñadirPersona extends javax.swing.JDialog {

    /**
     * Creates new form AñadirPersona
     */
    public AñadirPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Añadir Persona");
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        this.clickAceptar=false;
        this.obj=null;
        setResizable(false);
        setVisible(true);
        setBounds(parent.getWidth()/2-this.getWidth()/2,parent.getHeight()/2-this.getHeight()/2,this.getWidth(),this.getHeight());
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenido = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jLabelAltura = new javax.swing.JLabel();
        jTextFieldHeigth = new javax.swing.JTextField();
        jPanelBotones = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanelContenido.setLayout(new java.awt.GridLayout(3, 2));

        jLabelNombre.setText("Nombre:");
        jPanelContenido.add(jLabelNombre);

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jPanelContenido.add(jTextFieldName);

        jLabelEdad.setText("Edad:");
        jPanelContenido.add(jLabelEdad);

        jTextFieldAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgeActionPerformed(evt);
            }
        });
        jPanelContenido.add(jTextFieldAge);

        jLabelAltura.setText("Altura");
        jPanelContenido.add(jLabelAltura);

        jTextFieldHeigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHeigthActionPerformed(evt);
            }
        });
        jPanelContenido.add(jTextFieldHeigth);

        getContentPane().add(jPanelContenido);

        jPanelBotones.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanelBotones.setMinimumSize(new java.awt.Dimension(0, 80));
        jPanelBotones.setPreferredSize(new java.awt.Dimension(400, 80));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Campos llenados");

        jLabel2.setText("incorrectamente");
        jLabel2.setMaximumSize(new java.awt.Dimension(97, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(97, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(97, 16));

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addGap(39, 39, 39)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanelBotones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       if(ValidarPersona() && this.obj!=null){
           this.clickAceptar=true;
           dispose();
       } else{
           jLabel1.setVisible(true);
           jLabel2.setVisible(true);
       }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      this.clickAceptar=false;
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
       
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
      
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jTextFieldHeigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHeigthActionPerformed
        
    }//GEN-LAST:event_jTextFieldHeigthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirPersona dialog = new AñadirPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private boolean clickAceptar;
    private Persona obj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldHeigth;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    private boolean ValidarPersona() {
        boolean validador = true;
        boolean valage = true;
        boolean valheigth = true;
        String name = jTextFieldName.getText();
        String s = jTextFieldAge.getText();
        int age=0;
        double heigth=0;
        try {
            age = Integer.parseInt(s.trim());

        } catch (Exception e) {
            valage = false;
        }
        String z = jTextFieldHeigth.getText();
        try {
            heigth = Double.parseDouble(z.trim());

        } catch (Exception e) {
            valheigth = false;
        }
        if (name.trim().equals("") || name.isEmpty() == true || age==0 || heigth==0 ) {
            validador = false;
        }
        if (valage == false) {
            validador = false;
        }
        if (valheigth == false) {
            validador = false;
        }
        if (validador && valage && valheigth) {
                obj = new Persona(name, age, heigth);
       }
            
        return validador;
    }
    public boolean exec(){
        return clickAceptar;
    }
    public void setObj(Persona obj) {
        this.obj = obj;
    }
    public Persona getObj() {
        return obj;
    }
}
