/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curd_tarea;

import java.io.IOException;

import javax.print.DocFlavor.STRING;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("CRUD_persona");
        jPanelEliminacion.setVisible(false);
        jLabelErrorEliminar.setVisible(false);
        clickAceptarEli = false;
        controlador = new Controlador();
        actualizarFooter();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jButtonHeaderSalir = new javax.swing.JButton();
        jPanelContents = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonGenerarNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jPanelEliminacion = new javax.swing.JPanel();
        jTextFieldEliminacion = new javax.swing.JTextField();
        jLabelEliminacion = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelErrorEliminar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCantiddaPersonas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanelHeader.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanelHeader.setMinimumSize(new java.awt.Dimension(0, 40));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(600, 40));

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("Guarda los nuevos datos");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCargar.setText("Cargar");
        jButtonCargar.setToolTipText("Carga los datos previamente guardados");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jButtonHeaderSalir.setBackground(new java.awt.Color(255, 51, 51));
        jButtonHeaderSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonHeaderSalir.setText("Salir");
        jButtonHeaderSalir.setToolTipText("");
        jButtonHeaderSalir.setFocusPainted(false);
        jButtonHeaderSalir.setInheritsPopupMenu(true);
        jButtonHeaderSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHeaderSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(jPanelHeaderLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup().addComponent(jButtonGuardar).addGap(0, 0, 0)
                        .addComponent(jButtonCargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                        .addComponent(jButtonHeaderSalir).addContainerGap()));
        jPanelHeaderLayout.setVerticalGroup(jPanelHeaderLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHeaderLayout.createSequentialGroup().addGap(7, 7, 7)
                        .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonGuardar)
                                .addGroup(jPanelHeaderLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonCargar).addComponent(jButtonHeaderSalir)))));

        getContentPane().add(jPanelHeader);

        jPanelContents.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContents.setLayout(new javax.swing.BoxLayout(jPanelContents, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanelContents);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButtonGenerarNuevo.setText("Añadir Persona");
        jButtonGenerarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarNuevoActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar Persona");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelEliminacion.setText("Nombre de quien va a eliminar:");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelErrorEliminar.setText("Nombre inválido.");

        javax.swing.GroupLayout jPanelEliminacionLayout = new javax.swing.GroupLayout(jPanelEliminacion);
        jPanelEliminacion.setLayout(jPanelEliminacionLayout);
        jPanelEliminacionLayout.setHorizontalGroup(jPanelEliminacionLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEliminacionLayout.createSequentialGroup().addContainerGap()
                        .addGroup(jPanelEliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelEliminacion, javax.swing.GroupLayout.DEFAULT_SIZE, 197,
                                        Short.MAX_VALUE)
                                .addComponent(jTextFieldEliminacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        jPanelEliminacionLayout.createSequentialGroup().addComponent(jButtonCancelar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonAceptar))
                                .addComponent(jLabelErrorEliminar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap()));
        jPanelEliminacionLayout.setVerticalGroup(jPanelEliminacionLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminacionLayout.createSequentialGroup()
                        .addContainerGap().addComponent(jLabelEliminacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelErrorEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(
                                jPanelEliminacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAceptar).addComponent(jButtonCancelar))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGenerarNuevo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanelEliminacion, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup().addContainerGap().addComponent(jButtonGenerarNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminar).addGap(18, 18, 18)
                        .addComponent(jPanelEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1.add(jPanel2);

        jPanel3.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 480));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "Nombre", "Edad", "Altura" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.Integer.class, java.lang.Double.class };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jTable1.setName("Perssonas"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addContainerGap()));
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jScrollPane1,
                        javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)));

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        jPanelFooter.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanelFooter.setMinimumSize(new java.awt.Dimension(0, 80));
        jPanelFooter.setPreferredSize(new java.awt.Dimension(600, 80));
        jPanelFooter.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Cantidad de personas:");
        jPanelFooter.add(jLabel2);

        jLabelCantiddaPersonas.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabelCantiddaPersonas.setText("0");
        jPanelFooter.add(jLabelCantiddaPersonas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("Desarrollado por:");
        jPanelFooter.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Reyson Hdz Villa");
        jPanelFooter.add(jLabel3);

        getContentPane().add(jPanelFooter);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHeaderSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonHeaderSalirActionPerformed
        dispose();
    }// GEN-LAST:event_jButtonHeaderSalirActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCargarActionPerformed
        Cargar dialog = new Cargar(this, true);

        boolean aceptado = dialog.exec();
        if (aceptado == true) {
            String s = dialog.getS();
            if (s.trim().equals("") || s.isEmpty() == true) {
           }else{
            try {
                this.controlador.setGrupo(this.controlador.Importar(this.controlador.getGrupo(), s));
               } catch (ClassNotFoundException | IOException e) {
               }
               actualizarFooter();
               actualizarTabla();
           }
       }
    }// GEN-LAST:event_jButtonCargarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonGuardarActionPerformed
        Guardado diaolog = new Guardado(this, true);

        boolean acepted = diaolog.exec();
        if (acepted == true) {
            String s = diaolog.getS();
            if (s.trim().equals("") || s.isEmpty() == true) {
            } else {
                try {
                    controlador.Exportar(controlador.getGrupo(), s);

                } catch (IOException e) {
                }
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGenerarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarNuevoActionPerformed
     AñadirPersona dialog=new AñadirPersona(this,true);

     boolean acepted=dialog.exec();
     if(acepted==true){
       Persona per=dialog.getObj();
       if(per!=null){
          this.controlador.addPersona(per);
          actualizarTabla();
          actualizarFooter();
       }
    }
     
    }//GEN-LAST:event_jButtonGenerarNuevoActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        jPanelEliminacion.setVisible(true);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
       if (validarEliminacion()==true) {
           this.controlador.deletePersona(jTextFieldEliminacion.getText().trim());
           jPanelEliminacion.setVisible(false);   
           actualizarTabla();
           actualizarFooter();
           jTextFieldEliminacion.setText("");
       }else{
           jLabelErrorEliminar.setVisible(true);
       }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jPanelEliminacion.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

  
   
    private boolean clickAceptarEli;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGenerarNuevo;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonHeaderSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCantiddaPersonas;
    private javax.swing.JLabel jLabelEliminacion;
    private javax.swing.JLabel jLabelErrorEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelContents;
    private javax.swing.JPanel jPanelEliminacion;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldEliminacion;
    // End of variables declaration//GEN-END:variables

    private void actualizarFooter() {
        String s=String.valueOf(controlador.getGrupo().length);
        if (s.equals("")||s.equals(" ")||s.equals(null)||s.equals("0")) {
            jLabelCantiddaPersonas.setText("0");
        }else{
            jLabelCantiddaPersonas.setText(s);
        }
    }
    private void actualizarTabla() {
        Object [] nombreCol= {"Nombre","Edad","Altrua"};
 
        DefaultTableModel model=new DefaultTableModel(nombreCol, 0);

        for (int i = 0; i < this.controlador.getGrupo().length ; i++) {

            String name=this.controlador.getGrupo()[i].getName();
            String age=String.valueOf(this.controlador.getGrupo()[i].getEdad());
            String altrua=Double.toString(this.controlador.getGrupo()[i].getAltura());
            Object [] fila={name,age,altrua};
            model.addRow(fila);
        }
        jTable1.setModel(model);
    }
    private boolean validarEliminacion(){
        boolean vali=true;
        if(jTextFieldEliminacion.getText().trim().equals("")){
            vali=false;
        }
        if( this.controlador.getGrupo().length>0){
            for (int i = 0; i < this.controlador.getGrupo().length; i++) {
                  if(jTextFieldEliminacion.getText().trim().equals(this.controlador.getGrupo()[i].getName().trim())){
                      vali=true;
                      return vali;
                  }else{
                      vali=false;
                  }
            }
        }else{
            vali=false;
        }
        
        return vali;
    }
    public Controlador getControlador() {
        return controlador;
    }
}
